name: Render Rmd

on:
  workflow_dispatch:  # Permet de lancer à la main

jobs:
  render:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Install rmarkdown
        run: |
          install.packages("rmarkdown")
        shell: Rscript {0}

      - name: Render Rmd
        run: |
          rmarkdown::render("rapport.Rmd", output_format = "html_document")
        shell: Rscript {0}

      - name: Commit result
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add rapport.html
          git commit -m "Render Rmd via GitHub Action"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
